# Generated by Django 2.2 on 2021-07-16 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_master_minds', '0003_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_master_minds.User')),
                ('quiz', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_master_minds.Quiz')),
            ],
        ),
    ]
