# Generated by Django 2.2 on 2021-07-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_master_minds', '0004_auto_20210716_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
