# Generated by Django 2.2 on 2021-07-20 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_master_minds', '0007_auto_20210718_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='answer',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='answer_2',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_4',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_5',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_4',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_5',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
